# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: DarkFox
email: darkfox@darkfox.dk
description: "Developer, geek, tinkerer, and furry."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://darkfox.dk" # the base hostname & protocol for your site
github_username:  DarkFox
twitter_username: DarkFox
facebook_username: DarkFoxDK
linkedin_username: DarkFox
furry_mastodon_url: https://vulpine.club/@darkfox
personal_mastodon_url: https://tech.lgbt/@TroelsEberhardt
timezone: 'Europe/Copenhagen'

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/


# Includes
include: .well-known
